apiVersion: apps/v1
kind: Deployment
metadata:
  name: uptime-monitor-backend
  namespace: uptime-monitor
spec:
  replicas: 1
  selector:
    matchLabels:
      app: uptime-monitor-backend
  template:
    metadata:
      labels:
        app: uptime-monitor-backend
    spec:
      containers:
        - name: uptime-monitor-backend
          image: uptime-monitor-backend:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          env:
            - name: DATABASE_URL
              value: postgresql+psycopg://uptime_user:local_dev_password@uptime-monitor-postgres:5432/uptime_monitor
