apiVersion: v1
kind: Service
metadata:
  name: uptime-monitor-frontend
  namespace: uptime-monitor
spec:
  selector:
    app: uptime-monitor-frontend
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: NodePort