apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-monitor-backend
  namespace: uptime-monitor
  annotations:
    nginx.ingress.kubernetes.io/use-regex: "true"
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  ingressClassName: nginx
  rules:
    - host: uptime.local
      http:
        paths:
          - path: /api(/|$)(.*)
            pathType: ImplementationSpecific
            backend:
              service:
                name: uptime-monitor-backend
                port:
                  number: 8000

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: uptime-monitor-frontend
  namespace: uptime-monitor
spec:
  ingressClassName: nginx
  rules:
    - host: uptime.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: uptime-monitor-frontend
                port:
                  number: 80